# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c22a4fad3a55da8aba133fd8798415a7f7ea477239536e5eff0afdb1b0e31d94add507a6d72ea63fdf19de14379a42a93f3dbfc4514f90dc993a34c7a5ae368a

test:
  secret_key_base: ffd86045c06065d12b6430c8be480326dc871c699a4fb8a3bc11ea4f7cb408534086a1ed4a198a3dca6ccddd3c7311a304f5279a509640958edf14854ea5e766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
